# Site settings
title: DongYeo's Blog
header-img: img/home-bg.jpg
email: linxury@foxmail.com
description: "Code never lies to me."
baseurl: ""
url: "http://localhost:4000"
twitter_username:
github_username:  dongyeo
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
gems: ["jekyll-paginate"]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
